name: ZAdditions
version: 1.0
main: me.nicolas.zAdditions.ZAdditions
api-version: 1.19
author: Emojiado
commands:
  chunkminer:
    description: Sistema de Chunk Miner
    usage: |
      §e/chunkminer [cantidad] §7- Obtener Chunk Miners
      §e/chunkminer give <jugador> [cantidad] §7- Dar Chunk Miners a otro jugador
      §e/chunkminer pause §7- Pausar todos los Chunk Miners
      §e/chunkminer start §7- Reactivar todos los Chunk Miners
      §e/chunkminer status §7- Ver estado de los Chunk Miners
      §e/chunkminer reset §7- Resetear todos los Chunk Miners (solo consola)
permissions:
  zadditions.chunkminer.give:
    description: Permite obtener Chunk Miners
    default: op
  zadditions.chunkminer.give.others:
    description: Permite dar Chunk Miners a otros jugadores
    default: op
  zadditions.chunkminer.manage:
    description: Permite pausar y reactivar Chunk Miners
    default: op
  zadditions.chunkminer.place:
    description: Permite colocar Chunk Miners
    default: true
  zadditions.chunkminer.admin:
    description: Permite administrar Chunk Miners de otros jugadores
    default: op